apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector: # finds any pod with this label app: webapp and attaches the service to it
    app: webapp
  ports:
  - name: http
    port: 80
    nodePort: 30080 # must be > 30,000 to avoid port clashes 
  type: NodePort # expose port through the node i.e. public, vs private ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
  ports:
  - name: http
    port: 8161
    nodePort: 30010
  
  - name: endpoint
    port: 61616

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
  ports:
  - name: http
    port: 8080
    
  type: ClusterIP